# Stack Name: heis-o-mat
# Description: Automate your heise+ archive. Seamlessly fetch and organize c't, iX, and Make magazines for your local digital library. Paid heise+ subscription needed.
#
services:
  # -----------------------------
  # heis-o-mat
  # -----------------------------
  # GitHub: https://github.com/sir106/Heis-O-Mat
  # DockerHub:
  # Docs:
  # Howto:
  #
  heis-o-mat:
    image: alpine:latest
    container_name: heis-o-mat
    # restart: unless-stopped


    volumes:
      # VOLUMES default
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      # VOLUMES heis-o-mat
      - ${SERVER_VOLUME}:/downloads

    environment:
      # ENVIRONMENT heis-o-mat
      - TZ=Europe/Berlin
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8

      # ENVIRONMENT XYZ
      - HEISE_USERNAME=${HEISE_USERNAME}
      - HEISE_PASSWORD=${HEISE_PASSWORD}
      - REPO_URL=${REPO_URL:-https://github.com/sir106/Heis-O-Mat}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR:-/downloads}
      - APPRISE_URL=${APPRISE_URL}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-"0 10 * * 6"}
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo ============" Init heis-o-mat ============"

        # Install packages
        echo "[INIT] Installing packages..."
        apk add --no-cache git curl bash coreutils ca-certificates python3 py3-pip py3-requests py3-dotenv;
        update-ca-certificates;
        echo "Packages installed successfully."

        # Cron_Schedule Setzen
        CRON_SCHEDULE=${CRON_SCHEDULE:-"0 10 * * 6"}

        # 2. Clone repo
        echo "[INIT] Checking for repository at /app..."
        mkdir -p /app
        if [ ! -d '/app/.git' ]; then
          echo "Cloning repository from $${REPO_URL}..."
          git clone $${REPO_URL} /app;
        else
          echo "Repository already exists."
        fi
        echo "[INIT] Making start-downloads.sh executable..."
        chmod +x /app/start-downloads.sh;

        # Docker-Umgebungsvariablen für Cron verfügbar machen
        printenv > /etc/environment

        # 3. Setup cronjob
        echo "[INIT] Configuring cronjob..."
        mkdir -p /var/spool/cron/crontabs
        echo "$CRON_SCHEDULE /app/start-downloads.sh > /proc/1/fd/1 2>&1" > /var/spool/cron/crontabs/root
        echo "Cronjob configured ($CRON_SCHEDULE)."


        echo "Starting initial download in the background..."
        /app/start-downloads.sh &

        echo ============" Initialization finished. heis-o-mat ready ============"

        # Crond in foreground
        echo "Waiting for next cronjob.."
        exec crond -f -l 2

# ------------------------------
# Volumes
# ------------------------------
#volumes:
#  heis-o-mat_data:
#    driver: local

# ------------------------------
# Networks
# ------------------------------
networks:
  traefik_proxy:
    external: true
